"""Generate unique production secrets for a clinic Server install.

Writes %ProgramData%\\NKDentalSoft\\config\\.env (or --out path).
Never reuses docker-compose / development defaults.
"""

from __future__ import annotations

import argparse
import secrets
import sys
from pathlib import Path

LEGACY_MAINTENANCE_KEY = "Solo,yo1532"
JWT_MIN = 32
MAINT_MIN = 16


def _default_env_path() -> Path:
    program_data = Path(os_environ_programdata())
    return program_data / "NKDentalSoft" / "config" / ".env"


def os_environ_programdata() -> str:
    import os

    return os.environ.get("PROGRAMDATA") or r"C:\ProgramData"


def generate_secrets() -> tuple[str, str]:
    jwt_secret = secrets.token_hex(32)  # 64 hex chars
    maint = secrets.token_urlsafe(24)
    if maint == LEGACY_MAINTENANCE_KEY or len(maint) < MAINT_MIN:
        maint = secrets.token_urlsafe(32)
    if len(jwt_secret) < JWT_MIN:
        raise RuntimeError("JWT_SECRET generation failed length check")
    if maint == LEGACY_MAINTENANCE_KEY:
        raise RuntimeError("Refusing legacy maintenance key")
    return jwt_secret, maint


def write_env(
    path: Path,
    *,
    jwt_secret: str,
    maintenance_key: str,
    port: int = 8001,
    host: str = "0.0.0.0",
) -> None:
    if maintenance_key.strip() == LEGACY_MAINTENANCE_KEY:
        raise SystemExit("ERROR: MAINTENANCE_ACCESS_KEY legacy value is not allowed")
    if len(jwt_secret) < JWT_MIN:
        raise SystemExit(f"ERROR: JWT_SECRET must be ≥{JWT_MIN} characters")
    if len(maintenance_key) < MAINT_MIN:
        raise SystemExit(f"ERROR: MAINTENANCE_ACCESS_KEY must be ≥{MAINT_MIN} characters")

    data_dir = path.parent.parent / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    db_url = f"sqlite:///{(data_dir / 'clinica.db').as_posix()}"
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        [
            "# Generated by N&K DentalSoft Server installer — do not commit",
            "APP_ENV=production",
            f"JWT_SECRET={jwt_secret}",
            f"MAINTENANCE_ACCESS_KEY={maintenance_key}",
            f"DATABASE_URL={db_url}",
            f"BACKEND_PORT={port}",
            f"HOST={host}",
            "CORS_ORIGINS=*",
            "# Desktop: UI is same-origin on :8001 — leave frontend NEXT_PUBLIC_API_URL empty",
            "PASSWORD_RESET_INLINE_CODE=false",
            "",
        ]
    )
    path.write_text(content, encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:
        pass


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate production .env for Server install")
    parser.add_argument("--out", type=Path, default=None, help="Output .env path")
    parser.add_argument("--port", type=int, default=8001)
    args = parser.parse_args(argv)
    out = args.out or _default_env_path()
    jwt_secret, maint = generate_secrets()
    write_env(out, jwt_secret=jwt_secret, maintenance_key=maint, port=args.port)
    print(f"Wrote production env: {out}")
    print("APP_ENV=production")
    print(f"JWT_SECRET length={len(jwt_secret)}")
    print(f"MAINTENANCE_ACCESS_KEY length={len(maint)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
