"""initial schema all tables

Revision ID: 2905d1e9dd7e
Revises: 
Create Date: 2026-07-10 06:26:54.984390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2905d1e9dd7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_ficha', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=120), nullable=False),
    sa.Column('apellidos', sa.String(length=120), nullable=False),
    sa.Column('tipo_documento', sa.String(length=15), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=180), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=255), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_numero_documento'), 'patients', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_patients_numero_ficha'), 'patients', ['numero_ficha'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('recordatorio_enviado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_fecha_hora'), 'appointments', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('monto_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('abierta_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cerrada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinical_evolution_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('especialidad', sa.String(length=80), nullable=True),
    sa.Column('tratamiento_descripcion', sa.Text(), nullable=False),
    sa.Column('costo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('a_cuenta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('proxima_cita_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_evolution_entries_patient_id'), 'clinical_evolution_entries', ['patient_id'], unique=False)
    op.create_table('clinical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('antecedentes_medicos', sa.Text(), nullable=True),
    sa.Column('antecedentes_odontologicos', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('doctor_responsable_id', sa.Integer(), nullable=True),
    sa.Column('consentimiento_firmado', sa.Boolean(), nullable=False),
    sa.Column('consentimiento_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_responsable_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('documents_generated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('archivo_ref', sa.String(length=500), nullable=False),
    sa.Column('marcado_enviado_whatsapp_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('odontogram_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('pieza_fdi', sa.String(length=4), nullable=False),
    sa.Column('estado', sa.String(length=40), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odontogram_entries_patient_id'), 'odontogram_entries', ['patient_id'], unique=False)
    op.create_table('appointment_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('programado_para', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mensaje_sugerido', sa.Text(), nullable=False),
    sa.Column('marcado_enviado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('marcado_enviado_por_user_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['marcado_enviado_por_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_transactions_cash_session_id'), 'cash_transactions', ['cash_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_transactions_cash_session_id'), table_name='cash_transactions')
    op.drop_table('cash_transactions')
    op.drop_table('appointment_reminders')
    op.drop_index(op.f('ix_odontogram_entries_patient_id'), table_name='odontogram_entries')
    op.drop_table('odontogram_entries')
    op.drop_table('documents_generated')
    op.drop_table('clinical_records')
    op.drop_index(op.f('ix_clinical_evolution_entries_patient_id'), table_name='clinical_evolution_entries')
    op.drop_table('clinical_evolution_entries')
    op.drop_table('cash_sessions')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_fecha_hora'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_numero_ficha'), table_name='patients')
    op.drop_index(op.f('ix_patients_numero_documento'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
