/**
 * Infer sexo (M/F) from common Spanish/Latino given names.
 * First token of "nombres" is used. User can always override in the UI.
 */

export type InferredSexo = "M" | "F";

function stripDiacritics(s: string): string {
  return s.normalize("NFD").replace(/\p{M}/gu, "");
}

function firstGivenName(nombres: string): string {
  const raw = (nombres || "").trim().split(/\s+/)[0] || "";
  return stripDiacritics(raw).toLowerCase().replace(/[^a-zñ]/g, "");
}

/** Common masculine first names (Perú / LatAm). */
const MALE_NAMES = new Set(
  [
    "aaron",
    "abel",
    "abraham",
    "adam",
    "adrian",
    "agustin",
    "alan",
    "alberto",
    "alejandro",
    "alex",
    "alexander",
    "alexis",
    "alfonso",
    "alfred",
    "alfredo",
    "alonso",
    "alvaro",
    "andres",
    "angel",
    "anthony",
    "antonio",
    "ariel",
    "arthur",
    "arturo",
    "benjamin",
    "bernardo",
    "brandon",
    "bruno",
    "bryan",
    "caleb",
    "carlos",
    "cesar",
    "christian",
    "christopher",
    "claudio",
    "cristian",
    "cristobal",
    "damian",
    "daniel",
    "dante",
    "david",
    "diego",
    "dylan",
    "edgar",
    "eduardo",
    "edward",
    "elias",
    "emerson",
    "emilio",
    "emmanuel",
    "enrique",
    "eric",
    "erik",
    "ernesto",
    "esteban",
    "ethan",
    "eugenio",
    "fabian",
    "fabrizio",
    "facundo",
    "felipe",
    "felix",
    "fernando",
    "francisco",
    "franco",
    "frank",
    "gabriel",
    "gael",
    "gerardo",
    "german",
    "giancarlo",
    "gino",
    "gonzalo",
    "gregorio",
    "guillermo",
    "gustavo",
    "hans",
    "hector",
    "henry",
    "hernan",
    "hugo",
    "ian",
    "ignacio",
    "isaac",
    "isaias",
    "ismael",
    "ivan",
    "jairo",
    "james",
    "jason",
    "javier",
    "jefferson",
    "jeremy",
    "jesus",
    "joaquin",
    "joel",
    "john",
    "jonatan",
    "jonathan",
    "jorge",
    "jose",
    "joseph",
    "joshua",
    "josue",
    "juan",
    "julian",
    "julio",
    "junior",
    "kevin",
    "kevin",
    "leonardo",
    "liam",
    "lorenzo",
    "lucas",
    "luciano",
    "luis",
    "manuel",
    "marcelo",
    "marco",
    "marcos",
    "mario",
    "martin",
    "mateo",
    "matias",
    "mauricio",
    "max",
    "maximiliano",
    "miguel",
    "milton",
    "nelson",
    "nestor",
    "nicolas",
    "noah",
    "omar",
    "oscar",
    "pablo",
    "patrick",
    "patricio",
    "paul",
    "pedro",
    "piero",
    "raul",
    "renato",
    "ricardo",
    "richard",
    "roberto",
    "rodrigo",
    "roger",
    "rolando",
    "roman",
    "ronald",
    "ruben",
    "samuel",
    "santiago",
    "saul",
    "sebastian",
    "sergio",
    "simon",
    "steve",
    "thiago",
    "thomas",
    "tomas",
    "ulises",
    "victor",
    "vincent",
    "vladimir",
    "walter",
    "william",
    "xavier",
    "yosef",
    "youssef",
  ].map((n) => stripDiacritics(n))
);

/** Common feminine first names. */
const FEMALE_NAMES = new Set(
  [
    "abby",
    "adriana",
    "agustina",
    "alejandra",
    "alexa",
    "alexandra",
    "alice",
    "alicia",
    "amanda",
    "amelia",
    "ana",
    "andrea",
    "angela",
    "angelica",
    "anita",
    "anna",
    "antonella",
    "antonia",
    "ariana",
    "barbara",
    "beatriz",
    "belen",
    "brenda",
    "camila",
    "carla",
    "carmen",
    "carolina",
    "catalina",
    "catherine",
    "cecilia",
    "celeste",
    "claudia",
    "constanza",
    "cristina",
    "daniela",
    "daphne",
    "deborah",
    "diana",
    "dolores",
    "edith",
    "elena",
    "elisa",
    "elizabeth",
    "emily",
    "emma",
    "erika",
    "esther",
    "eugenia",
    "eva",
    "evelyn",
    "fabiana",
    "fabiola",
    "fatima",
    "fernanda",
    "flor",
    "florencia",
    "gabriela",
    "giuliana",
    "gladys",
    "gloria",
    "graciela",
    "guadalupe",
    "hannah",
    "helena",
    "ines",
    "irene",
    "iris",
    "isabel",
    "isabella",
    "ivana",
    "jackie",
    "jacqueline",
    "jennifer",
    "jenny",
    "jessica",
    "jimena",
    "joana",
    "johana",
    "josefa",
    "josefina",
    "juana",
    "julia",
    "juliana",
    "julieta",
    "karina",
    "karla",
    "karen",
    "kate",
    "katherine",
    "katie",
    "kiara",
    "laura",
    "leticia",
    "liliana",
    "lina",
    "lisbeth",
    "liz",
    "lorena",
    "lourdes",
    "lucia",
    "luciana",
    "luisa",
    "luz",
    "magaly",
    "magdalena",
    "manuela",
    "marcela",
    "margarita",
    "maria",
    "mariana",
    "marianela",
    "maribel",
    "marina",
    "marisol",
    "maritza",
    "martha",
    "martina",
    "mayra",
    "melania",
    "melanie",
    "melisa",
    "melissa",
    "mercedes",
    "micaela",
    "michelle",
    "milagros",
    "miriam",
    "monica",
    "nadia",
    "nancy",
    "natalia",
    "nathaly",
    "nicole",
    "noelia",
    "norma",
    "olga",
    "olivia",
    "paola",
    "patricia",
    "paula",
    "paulina",
    "pilar",
    "querubin",
    "rachel",
    "raquel",
    "rebeca",
    "renata",
    "rita",
    "rocio",
    "romana",
    "rosa",
    "rosario",
    "roxana",
    "ruth",
    "sandra",
    "sara",
    "sarah",
    "sharon",
    "sheila",
    "silvia",
    "sofia",
    "sonia",
    "stephanie",
    "susana",
    "tatiana",
    "tere",
    "teresa",
    "valentina",
    "valeria",
    "vanesa",
    "vanessa",
    "veronica",
    "victoria",
    "virginia",
    "viviana",
    "xiomara",
    "yalina",
    "yamile",
    "yanina",
    "yesenia",
    "yolanda",
    "yvonne",
    "zoe",
  ].map((n) => stripDiacritics(n))
);

/** Male names that end with "a" (heuristic exceptions). */
const MALE_ENDING_A = new Set(
  ["joshua", "judas", "luca", "elisha", "jonah", "noah", "asia"].map((n) =>
    stripDiacritics(n)
  )
);

/** Female names that end with "o" / consonant (heuristic exceptions). */
const FEMALE_ENDING_O = new Set(
  ["consuelo", "amparo", "socorro", "pilar", "carmen", "ines", "beatriz", "luz", "cruz"].map(
    (n) => stripDiacritics(n)
  )
);

/**
 * Guess M/F from given names, or null if uncertain.
 * Uses: dictionary first, then simple Spanish ending heuristics.
 */
export function inferSexoFromNombres(nombres: string): InferredSexo | null {
  const name = firstGivenName(nombres);
  if (!name || name.length < 2) return null;

  if (FEMALE_NAMES.has(name)) return "F";
  if (MALE_NAMES.has(name)) return "M";

  // Compound first parts already covered by first token (María …, Juan …).
  if (MALE_ENDING_A.has(name)) return "M";
  if (FEMALE_ENDING_O.has(name)) return "F";

  if (name.endsWith("a") && !MALE_ENDING_A.has(name)) return "F";
  if (name.endsWith("o") && !FEMALE_ENDING_O.has(name)) return "M";

  // Diminutives: -ita / -ina often female; -ito often male.
  if (name.endsWith("ita") || name.endsWith("ina") || name.endsWith("ela")) return "F";
  if (name.endsWith("ito") || name.endsWith("ico")) return "M";

  return null;
}
